name: Java CI Pipeline

on:
  push:
    branches: [ "main", "phase-3" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: JDK 17 Kurulumu
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Java Kodunu Derle
      run: javac src/NotificationManager.java
